package cn.com.kxcomm.entity;

import java.util.Date;
import org.apache.commons.lang.builder.ToStringBuilder;

public class RightEntity {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tb_ringht.right_id
     *
     * @ibatorgenerated Fri Jun 18 19:26:01 CST 2010
     */
    private Integer rightId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tb_ringht.parent_id
     *
     * @ibatorgenerated Fri Jun 18 19:26:01 CST 2010
     */
    private Integer parentId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tb_ringht.right_name
     *
     * @ibatorgenerated Fri Jun 18 19:26:01 CST 2010
     */
    private String rightName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tb_ringht.url
     *
     * @ibatorgenerated Fri Jun 18 19:26:01 CST 2010
     */
    private String url;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tb_ringht.create_time
     *
     * @ibatorgenerated Fri Jun 18 19:26:01 CST 2010
     */
    private Date createTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tb_ringht.level
     *
     * @ibatorgenerated Fri Jun 18 19:26:01 CST 2010
     */
    private Short level;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tb_ringht.right_id
     *
     * @return the value of tb_ringht.right_id
     *
     * @ibatorgenerated Fri Jun 18 19:26:01 CST 2010
     */
    public Integer getRightId() {
        return rightId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tb_ringht.right_id
     *
     * @param rightId the value for tb_ringht.right_id
     *
     * @ibatorgenerated Fri Jun 18 19:26:01 CST 2010
     */
    public void setRightId(Integer rightId) {
        this.rightId = rightId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tb_ringht.parent_id
     *
     * @return the value of tb_ringht.parent_id
     *
     * @ibatorgenerated Fri Jun 18 19:26:01 CST 2010
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tb_ringht.parent_id
     *
     * @param parentId the value for tb_ringht.parent_id
     *
     * @ibatorgenerated Fri Jun 18 19:26:01 CST 2010
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tb_ringht.right_name
     *
     * @return the value of tb_ringht.right_name
     *
     * @ibatorgenerated Fri Jun 18 19:26:01 CST 2010
     */
    public String getRightName() {
        return rightName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tb_ringht.right_name
     *
     * @param rightName the value for tb_ringht.right_name
     *
     * @ibatorgenerated Fri Jun 18 19:26:01 CST 2010
     */
    public void setRightName(String rightName) {
        this.rightName = rightName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tb_ringht.url
     *
     * @return the value of tb_ringht.url
     *
     * @ibatorgenerated Fri Jun 18 19:26:01 CST 2010
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tb_ringht.url
     *
     * @param url the value for tb_ringht.url
     *
     * @ibatorgenerated Fri Jun 18 19:26:01 CST 2010
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tb_ringht.create_time
     *
     * @return the value of tb_ringht.create_time
     *
     * @ibatorgenerated Fri Jun 18 19:26:01 CST 2010
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tb_ringht.create_time
     *
     * @param createTime the value for tb_ringht.create_time
     *
     * @ibatorgenerated Fri Jun 18 19:26:01 CST 2010
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tb_ringht.level
     *
     * @return the value of tb_ringht.level
     *
     * @ibatorgenerated Fri Jun 18 19:26:01 CST 2010
     */
    public Short getLevel() {
        return level;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tb_ringht.level
     *
     * @param level the value for tb_ringht.level
     *
     * @ibatorgenerated Fri Jun 18 19:26:01 CST 2010
     */
    public void setLevel(Short level) {
        this.level = level;
    }

	/**
	 * @see java.lang.Object#toString()
	 */
	public String toString() {
		return new ToStringBuilder(this).append("url", this.url).append(
				"createTime", this.createTime).append("rightName",
				this.rightName).append("rightId", this.rightId).append("level",
				this.level).append("parentId", this.parentId).toString();
	}
}