package cn.com.kxcomm.entity;

import org.apache.commons.lang.builder.ToStringBuilder;

public class RoleRinghtEntity {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tb_rs_role_ringht.right_id
     *
     * @ibatorgenerated Fri Jun 18 19:26:01 CST 2010
     */
    private Integer rightId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tb_rs_role_ringht.role_id
     *
     * @ibatorgenerated Fri Jun 18 19:26:01 CST 2010
     */
    private Integer roleId;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tb_rs_role_ringht.right_id
     *
     * @return the value of tb_rs_role_ringht.right_id
     *
     * @ibatorgenerated Fri Jun 18 19:26:01 CST 2010
     */
    public Integer getRightId() {
        return rightId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tb_rs_role_ringht.right_id
     *
     * @param rightId the value for tb_rs_role_ringht.right_id
     *
     * @ibatorgenerated Fri Jun 18 19:26:01 CST 2010
     */
    public void setRightId(Integer rightId) {
        this.rightId = rightId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tb_rs_role_ringht.role_id
     *
     * @return the value of tb_rs_role_ringht.role_id
     *
     * @ibatorgenerated Fri Jun 18 19:26:01 CST 2010
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tb_rs_role_ringht.role_id
     *
     * @param roleId the value for tb_rs_role_ringht.role_id
     *
     * @ibatorgenerated Fri Jun 18 19:26:01 CST 2010
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

	/**
	 * @see java.lang.Object#toString()
	 */
	public String toString() {
		return new ToStringBuilder(this).append("roleId", this.roleId).append(
				"rightId", this.rightId).toString();
	}
}