package com.etrack.mybatis.model;

public class Channel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_channel.id
     *
     * @mbggenerated Sat Jun 01 01:49:00 CST 2013
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_channel.name
     *
     * @mbggenerated Sat Jun 01 01:49:00 CST 2013
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_channel.com
     *
     * @mbggenerated Sat Jun 01 01:49:00 CST 2013
     */
    private String com;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_channel.id
     *
     * @return the value of tb_channel.id
     *
     * @mbggenerated Sat Jun 01 01:49:00 CST 2013
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_channel.id
     *
     * @param id the value for tb_channel.id
     *
     * @mbggenerated Sat Jun 01 01:49:00 CST 2013
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_channel.name
     *
     * @return the value of tb_channel.name
     *
     * @mbggenerated Sat Jun 01 01:49:00 CST 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_channel.name
     *
     * @param name the value for tb_channel.name
     *
     * @mbggenerated Sat Jun 01 01:49:00 CST 2013
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_channel.com
     *
     * @return the value of tb_channel.com
     *
     * @mbggenerated Sat Jun 01 01:49:00 CST 2013
     */
    public String getCom() {
        return com;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_channel.com
     *
     * @param com the value for tb_channel.com
     *
     * @mbggenerated Sat Jun 01 01:49:00 CST 2013
     */
    public void setCom(String com) {
        this.com = com;
    }
}