package com.etrack.mybatis.model;

import java.util.Date;

public class Orders {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_orders.id
	 * @mbggenerated  Tue Jun 04 13:16:23 CST 2013
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_orders.order_number
	 * @mbggenerated  Tue Jun 04 13:16:23 CST 2013
	 */
	private String orderNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_orders.agents_id
	 * @mbggenerated  Tue Jun 04 13:16:23 CST 2013
	 */
	private String agentsId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_orders.channel_id
	 * @mbggenerated  Tue Jun 04 13:16:23 CST 2013
	 */
	private String channelId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_orders.country_id
	 * @mbggenerated  Tue Jun 04 13:16:23 CST 2013
	 */
	private String countryId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_orders.status
	 * @mbggenerated  Tue Jun 04 13:16:23 CST 2013
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_orders.important
	 * @mbggenerated  Tue Jun 04 13:16:23 CST 2013
	 */
	private Integer important;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_orders.create_time
	 * @mbggenerated  Tue Jun 04 13:16:23 CST 2013
	 */
	private Date createTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_orders.id
	 * @return  the value of tb_orders.id
	 * @mbggenerated  Tue Jun 04 13:16:23 CST 2013
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_orders.id
	 * @param id  the value for tb_orders.id
	 * @mbggenerated  Tue Jun 04 13:16:23 CST 2013
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_orders.order_number
	 * @return  the value of tb_orders.order_number
	 * @mbggenerated  Tue Jun 04 13:16:23 CST 2013
	 */
	public String getOrderNumber() {
		return orderNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_orders.order_number
	 * @param orderNumber  the value for tb_orders.order_number
	 * @mbggenerated  Tue Jun 04 13:16:23 CST 2013
	 */
	public void setOrderNumber(String orderNumber) {
		this.orderNumber = orderNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_orders.agents_id
	 * @return  the value of tb_orders.agents_id
	 * @mbggenerated  Tue Jun 04 13:16:23 CST 2013
	 */
	public String getAgentsId() {
		return agentsId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_orders.agents_id
	 * @param agentsId  the value for tb_orders.agents_id
	 * @mbggenerated  Tue Jun 04 13:16:23 CST 2013
	 */
	public void setAgentsId(String agentsId) {
		this.agentsId = agentsId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_orders.channel_id
	 * @return  the value of tb_orders.channel_id
	 * @mbggenerated  Tue Jun 04 13:16:23 CST 2013
	 */
	public String getChannelId() {
		return channelId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_orders.channel_id
	 * @param channelId  the value for tb_orders.channel_id
	 * @mbggenerated  Tue Jun 04 13:16:23 CST 2013
	 */
	public void setChannelId(String channelId) {
		this.channelId = channelId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_orders.country_id
	 * @return  the value of tb_orders.country_id
	 * @mbggenerated  Tue Jun 04 13:16:23 CST 2013
	 */
	public String getCountryId() {
		return countryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_orders.country_id
	 * @param countryId  the value for tb_orders.country_id
	 * @mbggenerated  Tue Jun 04 13:16:23 CST 2013
	 */
	public void setCountryId(String countryId) {
		this.countryId = countryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_orders.status
	 * @return  the value of tb_orders.status
	 * @mbggenerated  Tue Jun 04 13:16:23 CST 2013
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_orders.status
	 * @param status  the value for tb_orders.status
	 * @mbggenerated  Tue Jun 04 13:16:23 CST 2013
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_orders.important
	 * @return  the value of tb_orders.important
	 * @mbggenerated  Tue Jun 04 13:16:23 CST 2013
	 */
	public Integer getImportant() {
		return important;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_orders.important
	 * @param important  the value for tb_orders.important
	 * @mbggenerated  Tue Jun 04 13:16:23 CST 2013
	 */
	public void setImportant(Integer important) {
		this.important = important;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_orders.create_time
	 * @return  the value of tb_orders.create_time
	 * @mbggenerated  Tue Jun 04 13:16:23 CST 2013
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_orders.create_time
	 * @param createTime  the value for tb_orders.create_time
	 * @mbggenerated  Tue Jun 04 13:16:23 CST 2013
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Override
	public String toString() {
		return "Orders [id=" + id + ", orderNumber=" + orderNumber
				+ ", agentsId=" + agentsId + ", channelId=" + channelId
				+ ", countryId=" + countryId + ", status=" + status
				+ ", important=" + important + ", createTime=" + createTime
				+ "]";
	}


    
}