package com.etrack.mybatis.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class OrdersExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tb_orders
	 * @mbggenerated  Tue Jun 04 13:16:23 CST 2013
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tb_orders
	 * @mbggenerated  Tue Jun 04 13:16:23 CST 2013
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tb_orders
	 * @mbggenerated  Tue Jun 04 13:16:23 CST 2013
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_orders
	 * @mbggenerated  Tue Jun 04 13:16:23 CST 2013
	 */
	public OrdersExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_orders
	 * @mbggenerated  Tue Jun 04 13:16:23 CST 2013
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_orders
	 * @mbggenerated  Tue Jun 04 13:16:23 CST 2013
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_orders
	 * @mbggenerated  Tue Jun 04 13:16:23 CST 2013
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_orders
	 * @mbggenerated  Tue Jun 04 13:16:23 CST 2013
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_orders
	 * @mbggenerated  Tue Jun 04 13:16:23 CST 2013
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_orders
	 * @mbggenerated  Tue Jun 04 13:16:23 CST 2013
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_orders
	 * @mbggenerated  Tue Jun 04 13:16:23 CST 2013
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_orders
	 * @mbggenerated  Tue Jun 04 13:16:23 CST 2013
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_orders
	 * @mbggenerated  Tue Jun 04 13:16:23 CST 2013
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_orders
	 * @mbggenerated  Tue Jun 04 13:16:23 CST 2013
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table tb_orders
	 * @mbggenerated  Tue Jun 04 13:16:23 CST 2013
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("id like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("id not like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<String> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<String> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andOrderNumberIsNull() {
			addCriterion("order_number is null");
			return (Criteria) this;
		}

		public Criteria andOrderNumberIsNotNull() {
			addCriterion("order_number is not null");
			return (Criteria) this;
		}

		public Criteria andOrderNumberEqualTo(String value) {
			addCriterion("order_number =", value, "orderNumber");
			return (Criteria) this;
		}

		public Criteria andOrderNumberNotEqualTo(String value) {
			addCriterion("order_number <>", value, "orderNumber");
			return (Criteria) this;
		}

		public Criteria andOrderNumberGreaterThan(String value) {
			addCriterion("order_number >", value, "orderNumber");
			return (Criteria) this;
		}

		public Criteria andOrderNumberGreaterThanOrEqualTo(String value) {
			addCriterion("order_number >=", value, "orderNumber");
			return (Criteria) this;
		}

		public Criteria andOrderNumberLessThan(String value) {
			addCriterion("order_number <", value, "orderNumber");
			return (Criteria) this;
		}

		public Criteria andOrderNumberLessThanOrEqualTo(String value) {
			addCriterion("order_number <=", value, "orderNumber");
			return (Criteria) this;
		}

		public Criteria andOrderNumberLike(String value) {
			addCriterion("order_number like", value, "orderNumber");
			return (Criteria) this;
		}

		public Criteria andOrderNumberNotLike(String value) {
			addCriterion("order_number not like", value, "orderNumber");
			return (Criteria) this;
		}

		public Criteria andOrderNumberIn(List<String> values) {
			addCriterion("order_number in", values, "orderNumber");
			return (Criteria) this;
		}

		public Criteria andOrderNumberNotIn(List<String> values) {
			addCriterion("order_number not in", values, "orderNumber");
			return (Criteria) this;
		}

		public Criteria andOrderNumberBetween(String value1, String value2) {
			addCriterion("order_number between", value1, value2, "orderNumber");
			return (Criteria) this;
		}

		public Criteria andOrderNumberNotBetween(String value1, String value2) {
			addCriterion("order_number not between", value1, value2,
					"orderNumber");
			return (Criteria) this;
		}

		public Criteria andAgentsIdIsNull() {
			addCriterion("agents_id is null");
			return (Criteria) this;
		}

		public Criteria andAgentsIdIsNotNull() {
			addCriterion("agents_id is not null");
			return (Criteria) this;
		}

		public Criteria andAgentsIdEqualTo(String value) {
			addCriterion("agents_id =", value, "agentsId");
			return (Criteria) this;
		}

		public Criteria andAgentsIdNotEqualTo(String value) {
			addCriterion("agents_id <>", value, "agentsId");
			return (Criteria) this;
		}

		public Criteria andAgentsIdGreaterThan(String value) {
			addCriterion("agents_id >", value, "agentsId");
			return (Criteria) this;
		}

		public Criteria andAgentsIdGreaterThanOrEqualTo(String value) {
			addCriterion("agents_id >=", value, "agentsId");
			return (Criteria) this;
		}

		public Criteria andAgentsIdLessThan(String value) {
			addCriterion("agents_id <", value, "agentsId");
			return (Criteria) this;
		}

		public Criteria andAgentsIdLessThanOrEqualTo(String value) {
			addCriterion("agents_id <=", value, "agentsId");
			return (Criteria) this;
		}

		public Criteria andAgentsIdLike(String value) {
			addCriterion("agents_id like", value, "agentsId");
			return (Criteria) this;
		}

		public Criteria andAgentsIdNotLike(String value) {
			addCriterion("agents_id not like", value, "agentsId");
			return (Criteria) this;
		}

		public Criteria andAgentsIdIn(List<String> values) {
			addCriterion("agents_id in", values, "agentsId");
			return (Criteria) this;
		}

		public Criteria andAgentsIdNotIn(List<String> values) {
			addCriterion("agents_id not in", values, "agentsId");
			return (Criteria) this;
		}

		public Criteria andAgentsIdBetween(String value1, String value2) {
			addCriterion("agents_id between", value1, value2, "agentsId");
			return (Criteria) this;
		}

		public Criteria andAgentsIdNotBetween(String value1, String value2) {
			addCriterion("agents_id not between", value1, value2, "agentsId");
			return (Criteria) this;
		}

		public Criteria andChannelIdIsNull() {
			addCriterion("channel_id is null");
			return (Criteria) this;
		}

		public Criteria andChannelIdIsNotNull() {
			addCriterion("channel_id is not null");
			return (Criteria) this;
		}

		public Criteria andChannelIdEqualTo(String value) {
			addCriterion("channel_id =", value, "channelId");
			return (Criteria) this;
		}

		public Criteria andChannelIdNotEqualTo(String value) {
			addCriterion("channel_id <>", value, "channelId");
			return (Criteria) this;
		}

		public Criteria andChannelIdGreaterThan(String value) {
			addCriterion("channel_id >", value, "channelId");
			return (Criteria) this;
		}

		public Criteria andChannelIdGreaterThanOrEqualTo(String value) {
			addCriterion("channel_id >=", value, "channelId");
			return (Criteria) this;
		}

		public Criteria andChannelIdLessThan(String value) {
			addCriterion("channel_id <", value, "channelId");
			return (Criteria) this;
		}

		public Criteria andChannelIdLessThanOrEqualTo(String value) {
			addCriterion("channel_id <=", value, "channelId");
			return (Criteria) this;
		}

		public Criteria andChannelIdLike(String value) {
			addCriterion("channel_id like", value, "channelId");
			return (Criteria) this;
		}

		public Criteria andChannelIdNotLike(String value) {
			addCriterion("channel_id not like", value, "channelId");
			return (Criteria) this;
		}

		public Criteria andChannelIdIn(List<String> values) {
			addCriterion("channel_id in", values, "channelId");
			return (Criteria) this;
		}

		public Criteria andChannelIdNotIn(List<String> values) {
			addCriterion("channel_id not in", values, "channelId");
			return (Criteria) this;
		}

		public Criteria andChannelIdBetween(String value1, String value2) {
			addCriterion("channel_id between", value1, value2, "channelId");
			return (Criteria) this;
		}

		public Criteria andChannelIdNotBetween(String value1, String value2) {
			addCriterion("channel_id not between", value1, value2, "channelId");
			return (Criteria) this;
		}

		public Criteria andCountryIdIsNull() {
			addCriterion("country_id is null");
			return (Criteria) this;
		}

		public Criteria andCountryIdIsNotNull() {
			addCriterion("country_id is not null");
			return (Criteria) this;
		}

		public Criteria andCountryIdEqualTo(String value) {
			addCriterion("country_id =", value, "countryId");
			return (Criteria) this;
		}

		public Criteria andCountryIdNotEqualTo(String value) {
			addCriterion("country_id <>", value, "countryId");
			return (Criteria) this;
		}

		public Criteria andCountryIdGreaterThan(String value) {
			addCriterion("country_id >", value, "countryId");
			return (Criteria) this;
		}

		public Criteria andCountryIdGreaterThanOrEqualTo(String value) {
			addCriterion("country_id >=", value, "countryId");
			return (Criteria) this;
		}

		public Criteria andCountryIdLessThan(String value) {
			addCriterion("country_id <", value, "countryId");
			return (Criteria) this;
		}

		public Criteria andCountryIdLessThanOrEqualTo(String value) {
			addCriterion("country_id <=", value, "countryId");
			return (Criteria) this;
		}

		public Criteria andCountryIdLike(String value) {
			addCriterion("country_id like", value, "countryId");
			return (Criteria) this;
		}

		public Criteria andCountryIdNotLike(String value) {
			addCriterion("country_id not like", value, "countryId");
			return (Criteria) this;
		}

		public Criteria andCountryIdIn(List<String> values) {
			addCriterion("country_id in", values, "countryId");
			return (Criteria) this;
		}

		public Criteria andCountryIdNotIn(List<String> values) {
			addCriterion("country_id not in", values, "countryId");
			return (Criteria) this;
		}

		public Criteria andCountryIdBetween(String value1, String value2) {
			addCriterion("country_id between", value1, value2, "countryId");
			return (Criteria) this;
		}

		public Criteria andCountryIdNotBetween(String value1, String value2) {
			addCriterion("country_id not between", value1, value2, "countryId");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("status is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("status is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(Integer value) {
			addCriterion("status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(Integer value) {
			addCriterion("status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(Integer value) {
			addCriterion("status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(Integer value) {
			addCriterion("status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(Integer value) {
			addCriterion("status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<Integer> values) {
			addCriterion("status in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<Integer> values) {
			addCriterion("status not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(Integer value1, Integer value2) {
			addCriterion("status between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(Integer value1, Integer value2) {
			addCriterion("status not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andImportantIsNull() {
			addCriterion("important is null");
			return (Criteria) this;
		}

		public Criteria andImportantIsNotNull() {
			addCriterion("important is not null");
			return (Criteria) this;
		}

		public Criteria andImportantEqualTo(Integer value) {
			addCriterion("important =", value, "important");
			return (Criteria) this;
		}

		public Criteria andImportantNotEqualTo(Integer value) {
			addCriterion("important <>", value, "important");
			return (Criteria) this;
		}

		public Criteria andImportantGreaterThan(Integer value) {
			addCriterion("important >", value, "important");
			return (Criteria) this;
		}

		public Criteria andImportantGreaterThanOrEqualTo(Integer value) {
			addCriterion("important >=", value, "important");
			return (Criteria) this;
		}

		public Criteria andImportantLessThan(Integer value) {
			addCriterion("important <", value, "important");
			return (Criteria) this;
		}

		public Criteria andImportantLessThanOrEqualTo(Integer value) {
			addCriterion("important <=", value, "important");
			return (Criteria) this;
		}

		public Criteria andImportantIn(List<Integer> values) {
			addCriterion("important in", values, "important");
			return (Criteria) this;
		}

		public Criteria andImportantNotIn(List<Integer> values) {
			addCriterion("important not in", values, "important");
			return (Criteria) this;
		}

		public Criteria andImportantBetween(Integer value1, Integer value2) {
			addCriterion("important between", value1, value2, "important");
			return (Criteria) this;
		}

		public Criteria andImportantNotBetween(Integer value1, Integer value2) {
			addCriterion("important not between", value1, value2, "important");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("create_time is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("create_time is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterion("create_time =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterion("create_time <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterion("create_time >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("create_time >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterion("create_time <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("create_time <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<Date> values) {
			addCriterion("create_time in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<Date> values) {
			addCriterion("create_time not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterion("create_time between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("create_time not between", value1, value2,
					"createTime");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table tb_orders
	 * @mbggenerated  Tue Jun 04 13:16:23 CST 2013
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_orders
     *
     * @mbggenerated do_not_delete_during_merge Fri May 31 15:38:55 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}