package com.etrack.mybatis.client;

import com.etrack.mybatis.model.Channel;
import com.etrack.mybatis.model.ChannelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChannelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_channel
     *
     * @mbggenerated Sat Jun 01 01:49:00 CST 2013
     */
    int countByExample(ChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_channel
     *
     * @mbggenerated Sat Jun 01 01:49:00 CST 2013
     */
    int deleteByExample(ChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_channel
     *
     * @mbggenerated Sat Jun 01 01:49:00 CST 2013
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_channel
     *
     * @mbggenerated Sat Jun 01 01:49:00 CST 2013
     */
    int insert(Channel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_channel
     *
     * @mbggenerated Sat Jun 01 01:49:00 CST 2013
     */
    int insertSelective(Channel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_channel
     *
     * @mbggenerated Sat Jun 01 01:49:00 CST 2013
     */
    List<Channel> selectByExample(ChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_channel
     *
     * @mbggenerated Sat Jun 01 01:49:00 CST 2013
     */
    Channel selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_channel
     *
     * @mbggenerated Sat Jun 01 01:49:00 CST 2013
     */
    int updateByExampleSelective(@Param("record") Channel record, @Param("example") ChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_channel
     *
     * @mbggenerated Sat Jun 01 01:49:00 CST 2013
     */
    int updateByExample(@Param("record") Channel record, @Param("example") ChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_channel
     *
     * @mbggenerated Sat Jun 01 01:49:00 CST 2013
     */
    int updateByPrimaryKeySelective(Channel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_channel
     *
     * @mbggenerated Sat Jun 01 01:49:00 CST 2013
     */
    int updateByPrimaryKey(Channel record);
}