package cn.com.kxcomm.entity;

import java.util.Date;
import org.apache.commons.lang.builder.ToStringBuilder;

public class RoleEntity {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tb_role.role_id
     *
     * @ibatorgenerated Fri Jun 18 19:26:01 CST 2010
     */
    private Integer roleId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tb_role.role_name
     *
     * @ibatorgenerated Fri Jun 18 19:26:01 CST 2010
     */
    private String roleName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tb_role.operator_id
     *
     * @ibatorgenerated Fri Jun 18 19:26:01 CST 2010
     */
    private Long operatorId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tb_role.create_time
     *
     * @ibatorgenerated Fri Jun 18 19:26:01 CST 2010
     */
    private Date createTime;
    private Date updateTime;

    public Date getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tb_role.role_id
     *
     * @return the value of tb_role.role_id
     *
     * @ibatorgenerated Fri Jun 18 19:26:01 CST 2010
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tb_role.role_id
     *
     * @param roleId the value for tb_role.role_id
     *
     * @ibatorgenerated Fri Jun 18 19:26:01 CST 2010
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tb_role.role_name
     *
     * @return the value of tb_role.role_name
     *
     * @ibatorgenerated Fri Jun 18 19:26:01 CST 2010
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tb_role.role_name
     *
     * @param roleName the value for tb_role.role_name
     *
     * @ibatorgenerated Fri Jun 18 19:26:01 CST 2010
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tb_role.operator_id
     *
     * @return the value of tb_role.operator_id
     *
     * @ibatorgenerated Fri Jun 18 19:26:01 CST 2010
     */
    public Long getOperatorId() {
        return operatorId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tb_role.operator_id
     *
     * @param operatorId the value for tb_role.operator_id
     *
     * @ibatorgenerated Fri Jun 18 19:26:01 CST 2010
     */
    public void setOperatorId(Long operatorId) {
        this.operatorId = operatorId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tb_role.create_time
     *
     * @return the value of tb_role.create_time
     *
     * @ibatorgenerated Fri Jun 18 19:26:01 CST 2010
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tb_role.create_time
     *
     * @param createTime the value for tb_role.create_time
     *
     * @ibatorgenerated Fri Jun 18 19:26:01 CST 2010
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

	/**
	 * @see java.lang.Object#toString()
	 */
	public String toString() {
		return new ToStringBuilder(this).append("roleName", this.roleName)
				.append("operatorId", this.operatorId).append("createTime",
						this.createTime).append("roleId", this.roleId).append(
						"updateTime", this.updateTime).toString();
	}
}