package com.etrack.mybatis.client;

import com.etrack.mybatis.model.Orders;
import com.etrack.mybatis.model.OrdersExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrdersMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_orders
	 * @mbggenerated  Tue Jun 04 13:16:23 CST 2013
	 */
	int countByExample(OrdersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_orders
	 * @mbggenerated  Tue Jun 04 13:16:23 CST 2013
	 */
	int deleteByExample(OrdersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_orders
	 * @mbggenerated  Tue Jun 04 13:16:23 CST 2013
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_orders
	 * @mbggenerated  Tue Jun 04 13:16:23 CST 2013
	 */
	int insert(Orders record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_orders
	 * @mbggenerated  Tue Jun 04 13:16:23 CST 2013
	 */
	int insertSelective(Orders record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_orders
	 * @mbggenerated  Tue Jun 04 13:16:23 CST 2013
	 */
	List<Orders> selectByExample(OrdersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_orders
	 * @mbggenerated  Tue Jun 04 13:16:23 CST 2013
	 */
	Orders selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_orders
	 * @mbggenerated  Tue Jun 04 13:16:23 CST 2013
	 */
	int updateByExampleSelective(@Param("record") Orders record,
			@Param("example") OrdersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_orders
	 * @mbggenerated  Tue Jun 04 13:16:23 CST 2013
	 */
	int updateByExample(@Param("record") Orders record,
			@Param("example") OrdersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_orders
	 * @mbggenerated  Tue Jun 04 13:16:23 CST 2013
	 */
	int updateByPrimaryKeySelective(Orders record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_orders
	 * @mbggenerated  Tue Jun 04 13:16:23 CST 2013
	 */
	int updateByPrimaryKey(Orders record);
}