package com.etrack.mybatis.client;

import com.etrack.mybatis.model.OrderTracking;
import com.etrack.mybatis.model.OrderTrackingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderTrackingMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_order_tracking
	 * @mbggenerated  Sat Jun 01 01:35:32 CST 2013
	 */
	int countByExample(OrderTrackingExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_order_tracking
	 * @mbggenerated  Sat Jun 01 01:35:32 CST 2013
	 */
	int deleteByExample(OrderTrackingExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_order_tracking
	 * @mbggenerated  Sat Jun 01 01:35:32 CST 2013
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_order_tracking
	 * @mbggenerated  Sat Jun 01 01:35:32 CST 2013
	 */
	int insert(OrderTracking record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_order_tracking
	 * @mbggenerated  Sat Jun 01 01:35:32 CST 2013
	 */
	int insertSelective(OrderTracking record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_order_tracking
	 * @mbggenerated  Sat Jun 01 01:35:32 CST 2013
	 */
	List<OrderTracking> selectByExample(OrderTrackingExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_order_tracking
	 * @mbggenerated  Sat Jun 01 01:35:32 CST 2013
	 */
	OrderTracking selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_order_tracking
	 * @mbggenerated  Sat Jun 01 01:35:32 CST 2013
	 */
	int updateByExampleSelective(@Param("record") OrderTracking record,
			@Param("example") OrderTrackingExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_order_tracking
	 * @mbggenerated  Sat Jun 01 01:35:32 CST 2013
	 */
	int updateByExample(@Param("record") OrderTracking record,
			@Param("example") OrderTrackingExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_order_tracking
	 * @mbggenerated  Sat Jun 01 01:35:32 CST 2013
	 */
	int updateByPrimaryKeySelective(OrderTracking record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_order_tracking
	 * @mbggenerated  Sat Jun 01 01:35:32 CST 2013
	 */
	int updateByPrimaryKey(OrderTracking record);
}