package com.etrack.mybatis.model;

import java.util.Date;

public class OrderTracking {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_order_tracking.id
	 * @mbggenerated  Sat Jun 01 01:35:32 CST 2013
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_order_tracking.order_id
	 * @mbggenerated  Sat Jun 01 01:35:32 CST 2013
	 */
	private String orderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_order_tracking.information
	 * @mbggenerated  Sat Jun 01 01:35:32 CST 2013
	 */
	private String information;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_order_tracking.time
	 * @mbggenerated  Sat Jun 01 01:35:32 CST 2013
	 */
	private Date time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_order_tracking.ftime
	 * @mbggenerated  Sat Jun 01 01:35:32 CST 2013
	 */
	private Date ftime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_order_tracking.id
	 * @return  the value of tb_order_tracking.id
	 * @mbggenerated  Sat Jun 01 01:35:32 CST 2013
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_order_tracking.id
	 * @param id  the value for tb_order_tracking.id
	 * @mbggenerated  Sat Jun 01 01:35:32 CST 2013
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_order_tracking.order_id
	 * @return  the value of tb_order_tracking.order_id
	 * @mbggenerated  Sat Jun 01 01:35:32 CST 2013
	 */
	public String getOrderId() {
		return orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_order_tracking.order_id
	 * @param orderId  the value for tb_order_tracking.order_id
	 * @mbggenerated  Sat Jun 01 01:35:32 CST 2013
	 */
	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_order_tracking.information
	 * @return  the value of tb_order_tracking.information
	 * @mbggenerated  Sat Jun 01 01:35:32 CST 2013
	 */
	public String getInformation() {
		return information;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_order_tracking.information
	 * @param information  the value for tb_order_tracking.information
	 * @mbggenerated  Sat Jun 01 01:35:32 CST 2013
	 */
	public void setInformation(String information) {
		this.information = information;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_order_tracking.time
	 * @return  the value of tb_order_tracking.time
	 * @mbggenerated  Sat Jun 01 01:35:32 CST 2013
	 */
	public Date getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_order_tracking.time
	 * @param time  the value for tb_order_tracking.time
	 * @mbggenerated  Sat Jun 01 01:35:32 CST 2013
	 */
	public void setTime(Date time) {
		this.time = time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_order_tracking.ftime
	 * @return  the value of tb_order_tracking.ftime
	 * @mbggenerated  Sat Jun 01 01:35:32 CST 2013
	 */
	public Date getFtime() {
		return ftime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_order_tracking.ftime
	 * @param ftime  the value for tb_order_tracking.ftime
	 * @mbggenerated  Sat Jun 01 01:35:32 CST 2013
	 */
	public void setFtime(Date ftime) {
		this.ftime = ftime;
	}

	@Override
	public String toString() {
		return "OrderTracking [id=" + id + ", orderId=" + orderId
				+ ", information=" + information + "]";
	}
    
}